CREATE TABLE exsrh_recipe_steps(
	id int NOT NULL AUTO_INCREMENT,
	recipe_id int NOT NULL,
	recipe_step int NOT NULL,
	step_descrip VARCHAR(255) NULL,
	recipe_function int NOT NULL,
	p1 float NULL,
	p2 float NULL,
	p3 float NULL,
	t1 varchar(255) NULL,
	pause_action int NULL,
	p1unit VARCHAR(255) NULL,
	p2unit VARCHAR(255) NULL,
	p3unit VARCHAR(255) NULL,
	PRIMARY KEY (id));